### ISSUE TITLE
Compat: Interfering with independent pets (and probably others)

### ISSUE THREAD

**Issue by AzureMonument** [Ellivers/Pettable#1]
I've been loving the heck out of this mod, and recently saw another mod I'd also love the heck out of called independent pets. However, I've recently noticed an issue- with this mod installed it overrides independent pets normal shift+Rclick behavior, making me unable to make my pets move freely.

It'd be nice if there was a config for this mod to have the 'pet' action set to a hotkey, rather than simple shift+rightclicking. That, or if petting didn't override all otherr interactions of shift+rClick.

Thank you for your time and the mod~♫

**Comment by Ellivers** [comment]
Fixed in 1.3.0
