### ISSUE TITLE
Petting animals breaks eventually (?)

### ISSUE THREAD

**Issue by sleepingdragoninn** [Ellivers/Pettable#4]
Occasionally petting animals seems to not respond anymore - clicking the bound key wont play the animation / show particles.

Is there a valid config number for the cooldown to disable it entirely? I'm figuring it could be the reason somehow.

**Comment by sisby-folk** [comment]
Update: Players are reporting that changing skins using [Fabric Tailor](https://github.com/samolego/FabricTailor) and/or sleeping occasionally causes a break or a fix.

**Comment by Ellivers** [comment]
Can you still reproduce this? Otherwise, I'll close this issue.

**Comment by sleepingdragoninn** [comment]
feel free to close - no idea
