### ISSUE TITLE
Why is the Game Version 1.18.2 when the mod works perfectly on 1.19.2?

### ISSUE THREAD

**Issue by skunkmommy** [Ellivers/Pettable#6]
I noticed that you could download 1.19 versions. So I tried it and it worked. Only thing is config crashed my game but I just edited it manually. Can you fix this crash and set Game Version to 1.19.2 cus it totally works on there

**Comment by Ellivers** [comment]
The crash in 1.19.2 has now been fixed by updating MidnightConfig to the latest version.
